Assignment3
Kiransai-webonise/rails pull request #5
Opened 2022-08-09 10:07 UTC by Kiransai-webonise

2022-08-09 10:18 UTC, balakrishna-webonise commented
It does not seem to be correct. CRUD should be there in the engine not here.

2022-08-11 07:33 UTC, balakrishna-webonise requested changes

2022-08-11 07:33 UTC, balakrishna-webonise commented on microblog/Gemfile
> +gem "blogtype", path: '../../blogtype'
Do not commit this. This should be part of your local development.

2022-08-12 10:37 UTC, balakrishna-webonise requested changes

2022-08-12 10:37 UTC, balakrishna-webonise commented on microblog/app/overrides/blogtypecontroller_override.rb
> +    after_action :allow_iframe, only: :lookup
why do you need this here?

2022-08-16 14:55 UTC, balakrishna-webonise requested changes

2022-08-16 14:55 UTC, balakrishna-webonise commented on microblog/config/routes.rb
> +  mount Articles::Engine, at: "/types"
the engine should be mounted on **static_pages’** right ?

2022-08-16 14:55 UTC, balakrishna-webonise commented on microblog/Gemfile.lock
> +  remote: ../../blogtype
You should run bundle install once you update Gemfile. It's referring local path here.

2022-08-16 15:06 UTC, Kiransai-webonise commented on microblog/config/routes.rb
> +  mount Articles::Engine, at: "/types"
`  mount Articles::Engine, at: "/static_pages"
`
Do you need like this?

2022-08-16 15:16 UTC, balakrishna-webonise commented on microblog/config/routes.rb
> +  mount Articles::Engine, at: "/types"
Yes..

2022-08-18 16:18 UTC, balakrishna-webonise commented on microblog/Gemfile.lock
> +  remote: ../../blogtype
> You should run bundle install once you update Gemfile. It's referring local path here.

Did address this ?

2022-08-18 16:27 UTC, balakrishna-webonise approved these changes

2022-08-18 16:27 UTC, merged